name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]   # or "master" if that's your default

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # ✅ latest

      - name: Setup Pages
        uses: actions/configure-pages@v4   # ✅ latest

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3   # ✅ latest (was v2)

        with:
          path: .   # upload everything (index.html, etc.)

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   # ✅ latest
